name: WakaTime Stats

on:
  # Runs every day at midnight
  schedule:
    - cron: '0 0 * * *'
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  update-readme:
    name: Update Readme with WakaTime Stats
    runs-on: ubuntu-latest
    
    steps:
      - name: Update Readme with WakaTime Stats
        uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          # Optional: Customize the stats
          SHOW_TITLE: true
          SHOW_TIME: true
          SHOW_TOTAL: true
          SHOW_MASKED_TIME: true
          SHOW_COMMIT: false
          SHOW_DAYS_OF_WEEK: true
          SHOW_LANGUAGE: true
          SHOW_EDITORS: true
          SHOW_PROJECTS: true
          SHOW_OS: true
          SHOW_SHORT_INFO: true
          SHOW_LOC_CHART: false
